### ISSUE TITLE
Outreach to requestor

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-community/features-bazel#1]
Hello @mering! 👋

I noticed that you wanted to add a Bazel feature https://github.com/devcontainers-contrib/features/pull/496 and I figured you might be interested in this project.

**Comment by mering** [comment]
What is the relation to the https://github.com/devcontainers-contrib/features repository?

Is this org new? When I last checked, I didn't find Bazel in https://containers.dev/features but now this seems to be added there :smiley:

**Comment by jcbhmr** [comment]
The gist of it at present is:
- @devcontainers: the official Microsoft organization devoted to standardizing and managing official stuffs. they do the spec, a small set of official features + templates and some base images.
- @devcontainers-contrib: @danielbraun89's awesome collection of devcontainer features. currently limited by single-human bandwidth of the owner.
- @devcontainers-community: intended to be run by _many_ and cover anything not quite official-level popular

I've been reaching out to other peoples who have devcontainer features that i figured might be cool to bring under one umbrella.

https://github.com/devcontainers-community/features-dart-sdk/issues/1
https://github.com/devcontainers-community/features-surrealdb/issues/1
https://github.com/devcontainers-community/features-direnv/issues/1
https://github.com/devcontainers-community/features-llvm/issues/1

here's a discussion thingie since someone else had the same question https://github.com/orgs/devcontainers-community/discussions/7

> Is this org new? When I last checked, I didn't find Bazel in [containers.dev/features](https://containers.dev/features) but now this seems to be added there 😃

you're right! i only recently added this bazel feature 🤣 right before i made this issue in fact 😉
the org itself is a few months old but recently seen high activity

**Comment by mering** [comment]
This is awesome, happy to main the Bazel feature here!
