### ISSUE TITLE
Make it work on the Ubuntu base image

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-community/features-bazel#2]
Right now it appears to only work on the Debian PLAIN image
![image](https://github.com/devcontainers-community/features-bazel/assets/61068799/4ba69740-e633-4f16-ab1d-2e0e8073153b)

https://github.com/devcontainers-community/features-bazel/actions/workflows/test-feature.yml

@mering found another existing Bazel feature https://github.com/Balazs23/devcontainers-features/blob/main/src/bazel/install.sh that might be worth trying to just copy-paste and see if that works? 🤔

**Comment by jcbhmr** [comment]
There also appears to be a former devcontainer template using Bazel  https://github.com/microsoft/vscode-dev-containers/blob/main/containers/bazel/.devcontainer/Dockerfile

**Comment by mering** [comment]
> There also appears to be a former devcontainer template using Bazel https://github.com/microsoft/vscode-dev-containers/blob/main/containers/bazel/.devcontainer/Dockerfile

Thanks for the hint. I found this before and used it for inspiration of this Bazel feature.
